### ISSUE TITLE
old branches

### ISSUE THREAD

**Issue by PaLeroy** [moratodpg/ray_environments#40]
Hey Pablo,

I think we can delete the old plot branch.

What about your heuristic branch? 

Cheers

**Comment by moratodpg** [comment]
Let's keep the heur branch for the moment.
But we can delete the old plot branch.

**Comment by moratodpg** [comment]
Okay, I applied all required modifications for 'heur' in a new branch and deleted the old branch.
I consider this issue is then resolved.
