### ISSUE TITLE
Possibility to access trained models

### ISSUE THREAD

**Issue by ymahlau** [moratodpg/ray_environments#68]
Hi,

I like the implementation of IMP-MARL and that you made the training data of your runs accessible! Would it be possible to give access to the trained models as well? This would alleviate the need to retrain the models and make reproduction of the results very easy.

Yours
Yannik

**Comment by PaLeroy** [comment]
Hey Yannik,

Thanks for the kind words!

So, we released one trained model per seed/method/env.
You can find these best agents on [ZENODO](https://zenodo.org/records/8032339) in `best_agent_networks.zip`.

We'll update the [data README](https://github.com/moratodpg/imp_marl/blob/main/results_scripts/README.md) accordingly.

Do not hesitate to come back to us If needed.

Best,
Pascal

**Comment by ymahlau** [comment]
Thanks for the quick answer and providing the models!
